Repository Algorythms-Inc/pylack, pull requests merged in 2023-09, with the labels that each got.

#7 Testing
  check_os.sh
  pylack.zsh
Labels: enhancement

#9 Testing
  pylack/main.py
  test/text.py
Labels: enhancement

#10 added doc header and a description
  README.md
Labels: documentation

#11 shell argv condtion
  pylack.zsh
  pylack/__init__.py
  pylack/__pycache__/__init__.cpython-310.pyc
  pylack/__pycache__/main.cpython-310.pyc
  pylack/main.py
  pylack_test.py
Labels: enhancement

#12 fixed code alignment
  pylack.zsh
Labels: bug

#13 Testing
  pylack.sh
  pylack.zsh
  pylack/main.py
Labels: bug, enhancement

#14 removed shell ext
  pylack
  pylack_/__init__.py
  pylack_/__pycache__/__init__.cpython-310.pyc
  pylack_/__pycache__/main.cpython-310.pyc
  pylack_/main.py
  pylack_test.py
Labels: bug, enhancement

#15 docker
  Dockerfile
  __img__/structure.jpg
Labels: enhancement

#16 upraded version
  dist/pylack-0.0.1-py3-none-any.whl
  dist/pylack-0.0.1.tar.gz
  dist/pylack-0.0.3-py3-none-any.whl
  dist/pylack-0.0.3.tar.gz
  pyproject.toml
  requirements.txt
Labels: bug
